# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MLTicTacToe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MLTicTacToe

  # react-native
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork',

    # rest
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTSettings',
    'RCTVibration',
    'BatchedBridge',
    'RCTPushNotification',
    'RCTLinkingIOS',

    'DevSupport'
  ]

  # Pods for MLTicTacToe
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  target 'MLTicTacToeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MLTicTacToe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MLTicTacToe-tvOS

  target 'MLTicTacToe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
